service: scorpion-encounters # NOTE: update this with your service name

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getScorpion: # AWS Lambda function
    handler: handler.scorpion # Run scorpion function from handler.js
    events: # The Events that trigger this Function
      - http:
          path: scorpion
          method: get
resources:
  Resources:
    CognitoUserPoolCognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}_${self:provider.stage}_user_pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}_${self:provider.stage}_client
        UserPoolId:
          Ref: CognitoUserPoolCognitoUserPool
        GenerateSecret: false
