service: scorpion-encounters # NOTE: update this with your service name

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true # enable auto-packing of external modules

provider:
  name: aws
  runtime: nodejs8.10

functions:
  getScorpion: # AWS Lambda function
    handler: handler.scorpion # Run scorpion function from handler.js
    events: # The Events that trigger this Function
      - http:
          path: scorpion
          method: get
